// modules/birthday/birthdays.js
// month/day は 1始まり。name は自由テキスト。
// 2/29 は「うるう年でなければ 2/28 にお祝い」扱いにしています。
export const BIRTHDAYS = [
  { name: "めんみ", month: 1, day: 5 },
  { name: "まり", month: 1, day: 21 },
  { name: "のとカス", month: 1, day: 22 },
  { name: "とりちゃ", month: 1, day: 25 },
  { name: "とわち", month: 1, day: 25 },
  { name: "アレク", month: 1, day: 28 },
  { name: "どら", month: 1, day: 28 },
  { name: "紫陽花", month: 1, day: 31 },
  { name: "シグマ", month: 2, day: 4 },
  { name: "名も無き王子", month: 2, day: 7 },
  { name: "焼き鳥", month: 2, day: 9 },
  { name: "悪魔", month: 2, day: 9 },
  { name: "クシー", month: 2, day: 14 },
  { name: "あか", month: 2, day: 15 },
  { name: "luna", month: 2, day: 21 },
  { name: "ひなひな", month: 2, day: 27 },
  { name: "はる", month: 2, day: 28 },
  { name: "ビタミン", month: 3, day: 5 },
  { name: "みや", month: 3, day: 9 },
  { name: "さーにゃ", month: 3, day: 11 },
  { name: "小林", month: 3, day: 12 },
  { name: "ねこちゃん", month: 3, day: 13 },
  { name: "きゃめ", month: 3, day: 21 },
  { name: "みっちょ", month: 3, day: 26 },
  { name: "トトロ", month: 3, day: 28 },
  { name: "りんご", month: 4, day: 1 },
  { name: "しろっち", month: 4, day: 3 },
  { name: "まめ", month: 4, day: 7 },
  { name: "翡翠", month: 4, day: 7 },
  { name: "あいりす", month: 4, day: 8 },
  { name: "タキモット", month: 4, day: 28 },
  { name: "いぶたそ", month: 5, day: 3 },
  { name: "若草色", month: 5, day: 6 },
  { name: "しぐれ", month: 5, day: 14 },
  { name: "しの", month: 5, day: 16 },
  { name: "碧", month: 5, day: 23 },
  { name: "きぃ", month: 5, day: 24 },
  { name: "らゐ", month: 5, day: 24 },
  { name: "琥珀", month: 5, day: 26 },
  { name: "とりそぼろ", month: 5, day: 27 },
  { name: "しゅわ", month: 6, day: 8 },
  { name: "ふぶき", month: 6, day: 10 },
  { name: "フラノア", month: 6, day: 12 },
  { name: "おkiraく", month: 6, day: 14 },
  { name: "Nico", month: 6, day: 16 },
  { name: "澪", month: 6, day: 25 },
  { name: "ダーク", month: 7, day: 3 },
  { name: "にこにこ", month: 7, day: 22 },
  { name: "楓", month: 7, day: 23 },
  { name: "つかゆう", month: 7, day: 25 },
  { name: "ハヤト", month: 7, day: 26 },
  { name: "てぃの", month: 8, day: 4 },
  { name: "クロナギ", month: 8, day: 6 },
  { name: "夜猫", month: 8, day: 8 },
  { name: "シグれんこん", month: 8, day: 21 },
  { name: "ネココ", month: 8, day: 22 },
  { name: "ウルフ", month: 8, day: 25 },
  { name: "ヘルメット", month: 8, day: 25 },
  { name: "ゆっきー", month: 8, day: 27 },
  { name: "のにのに神", month: 9, day: 5 },
  { name: "エンジェるね", month: 9, day: 10 },
  { name: "ルーグ", month: 10, day: 1 },
  { name: "ヴェイン", month: 10, day: 3 },
  { name: "黒帯黒猫", month: 10, day: 5 },
  { name: "ポカリ", month: 10, day: 8 },
  { name: "そゆーず", month: 10, day: 10 },
  { name: "んぺそ", month: 10, day: 13 },
  { name: "こみや", month: 10, day: 16 },
  { name: "もす", month: 10, day: 19 },
  { name: "JOJO", month: 10, day: 29 },
  { name: "りりちよ", month: 11, day: 2 },
  { name: "しろりんご", month: 11, day: 3 },
  { name: "らいか", month: 11, day: 11 },
  { name: "まよまよ", month: 11, day: 20 },
  { name: "黄色い人", month: 11, day: 24 },
  { name: "セイ", month: 12, day: 1 },
  { name: "うるは", month: 12, day: 4 },
  { name: "たくしゃ", month: 12, day: 12 },
  { name: "ラギお", month: 12, day: 14 },
  { name: "nyan", month: 12, day: 29 },
  { name: "しゅんぺい", month: 12, day: 23 },
];

// 誕生日のメッセージ文面をカスタムしたい場合はここを編集
export function buildMessage(jstMonth, jstDay, names) {
  if (names.length === 1) {
    return `本日（${jstMonth}月${jstDay}日）は ${names[0]} の誕生日です。ギルドでお祝いしましょう！`;
  }
  return [
    `本日（${jstMonth}月${jstDay}日）は以下の方の誕生日です。ギルドでお祝いしましょう！`,
    ...names.map(n => `- ${n}`)
  ].join("\n");
}
